### ISSUE TITLE
将目前的翻译与原文同步

### ISSUE THREAD

**Issue by JuanitoFatas** [ruby-china/rails-guides#4]
以 `getting_started.md` 为例，把 `source/zh-CN/getting_started.md` 译文与原文 `source/getting_started.md` 同步。这是一项体力活，需一行一行过一遍。
- [ ] action_controller_overview.md
- [ ] action_mailer_basics.md
- [ ] action_view_overview.md
- [ ] active_record_basics.md
- [ ] active_record_callbacks.md
- [ ] active_record_migrations.md
- [ ] active_record_postgresql.md
- [ ] active_record_querying.md
- [ ] active_record_validations.md
- [ ] asset_pipeline.md
- [ ] association_basics.md
- [ ] caching_with_rails.md
- [ ] command_line.md
- [ ] configuring.md
- [ ] debugging_rails_applications.md
- [ ] form_helpers.md
- [ ] getting_started.md
- [ ] i18n.md
- [ ] layouts_and_rendering.md
- [ ] rails_on_rack.md
- [ ] routing.md
- [ ] security.md
- [ ] testing.md
- [ ] working_with_javascript_in_rails.md

**Comment by xianhaipan** [comment]
现在的这个版本是4.1.＊版本？和官方的4.2.1版本的同步进度哪里可以知晓？我想加入到这个工作中来。

**Comment by JuanitoFatas** [comment]
@xianhaipan 比較重要的是先把所有的指南都翻譯完畢，就可以把版本定下來，接著再來考慮更新。要不找篇翻譯翻譯？
